# Generated by Django 2.2.3 on 2019-07-24 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingCourses',
            new_name='TrainingCourse',
        ),
    ]
